/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.0-36-gc5039e158d-20231028"
#endif /* AVUTIL_FFVERSION_H */
